SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://root:Shjg%40123@10.2.2.157:3306/wechat_spider?charset=utf8'
SQLALCHEMY_COMMIT_TEARDOWN = True
SQLALCHEMY_TRACK_MODIFICATIONS = True
SQLALCHEMY_COMMIT_ON_TEARDOWN = True
